services:
  postgres:
    image: postgres:15-alpine
    container_name: nestdeploy-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestdeploy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestdeploy-api
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nestdeploy?schema=public
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data:
